#!/bin/bash

set -o pipefail
readonly auth=$(jq -r '.auths."${DOCKER_LOCAL_REPOSITORY:?}".auth' ~/.docker/config.json | base64 --decode)
curl --silent -L -u "$auth" https://api.${DOCKER_LOCAL_REPOSITORY:?}/v2/${1:?}/tags/list | \
    jq -r '.tags | join("\n")'
