#!/bin/bash

repoHost=${DOCKER_UPSTREAM_REPOSITORY%%/*}
repoPath=/${DOCKER_UPSTREAM_REPOSITORY#*/}

set -o pipefail
readonly auth=$(jq -r '.auths."${repoHost}".auth' ~/.docker/config.json | base64 --decode)
curl --silent -L -u "$auth" https://api.${repoHost}/v2${repoPath}/${1:?}/tags/list | \
    jq -r '.tags | join("\n")'
