#!/bin/sh

printUsage()
{
    cat <<HELPTEXT
Kill all running containers.
Usage: "$(basename "$1")" [-?|-h|--help]
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

containers=$(docker ps -q)
if [ ! "$containers" ]; then
    echo >&2 "No running containers."
    exit 1
fi

exec docker kill "$@" $containers
