#!/bin/sh

container=$(docker-locate "${1:?}"); shift

finally()
{
    docker rm $(docker ps -aq --filter name=temp_bash) 2>/dev/null
    docker rmi temp_bash
}
trap 'finally' EXIT

docker commit "$container" temp_bash || exit $?
docker run --name=temp_bash --entrypoint=bash -it temp_bash "$@"
