#!/bin/sh

printUsage()
{
    cat <<HELPTEXT
Kill and remove all running containers.
Usage: "$(basename "$1")" [-?|-h|--help]
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

docker-killall
docker-clean "$@"
