#!/bin/bash
printUsage()
{
    cat <<HELPTEXT
Completely remove layers of an image (and all tags pointing to it).
Usage: "$(basename "$1")" [OPTIONS] IMAGE [-?|-h|--help]
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

lastArg=${!#}
id=$(docker-locate-image "$lastArg")
[ "$id" ] || { echo >&2 "ERROR: Could not locate image \"$lastArg\""; exit 1; }

exec docker rmi "${@:1:$(($#-1))}" "$id"
