#!/bin/sh
# Source: http://blog.yohanliyanage.com/2015/05/docker-clean-up-after-yourself/

exec docker run -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/docker:/var/lib/docker --rm martin/docker-cleanup-volumes
