#!/bin/bash

secondToLastArg=; [ $# -gt 1 ] && eval secondToLastArg=\${$(($#-1))}
lastArg=; [ $# -gt 0 ] && lastArg=${!#}
docker tag "$secondToLastArg" "$lastArg" && docker push "${@:1:$(($#-2))}" "$lastArg"
