#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Kill all running containers.
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '[-?|-h|--help]'
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

containers=$(docker ps -q)
if [ ! "$containers" ]; then
    echo >&2 "No running containers."
    exit 1
fi

exec docker kill "$@" $containers
